markdown: pandoc
pandoc:
    skip: false
    bundle_permalink: ':slug.:output_ext'
    papersize: 'a6paper'
    sheetsize: 'a4paper'
    imposition: true
    binder: true
    covers_dir: 'images/covers'
    flags: '--csl=apa.csl --bibliography=ref.bib --smart -V lang=es
            --section-divs --email-obfuscation=references'
    site_flags: '--toc --template=_layouts/toc.html'
    outputs:
        pdf: '-V fontsize=8pt,a6paper,twoside
                -V documentclass=book
                -V geometry=hcentering
                -V geometry=bindingoffset=5mm
                --latex-engine=xelatex
                --table-of-contents
                --include-in-header=_layouts/header.tex
                --include-before-body=_layouts/license.tex'
#        epub: '--epub-chapter-level=2'
#       mediawiki:
#       rst:
#       latex: '-V fontsize=8pt,a6paper,twoside
#                 -V documentclass=book
#                 -V geometry=hcentering
#                 -V geometry=bindingoffset=1cm
#                 --latex-engine=xelatex
#                 --table-of-contents
#                 --include-in-header=_layouts/header.tex
#                 --include-before-body=_layouts/license.tex'

destination: /srv/http/utopia.partidopirata.com.ar
layouts:  ./_layouts
plugins:  ./_plugins

exclude: [ tmp ]

permalink: ":title.html"

lsi: false

torrent:
  file: utopiapirata.torrent
